### ISSUE TITLE
Dokumentasi Fitur

### ISSUE THREAD

**Issue by hadihammurabi** [hajirodeon/booking-pasien#1]
Halo, Om.

Ini keren banget. Boleh minta didokumentasikan fitur-fiturnya, Om?

**Comment by hajirodeon** [comment]
heheheh...

dokumentasinya belum saya susun mas.

masih ujicoba...



intinya itu bisa booking periksa dokter, baik via web dan via android.

**Comment by hadihammurabi** [comment]
Wahh iya, keren, Om. Pengen colab tapi lagi belum ada waktu untuk saat ini

**Comment by hajirodeon** [comment]
gpp... hehehe...

**Comment by hadihammurabi** [comment]
Karena diskusi gak berlanjut, saya izin tutup issue-nya ya, Om @hajirodeon

**Comment by hajirodeon** [comment]
ok
